openapi: 3.0.0
info:
  title: Recipe App API
  version: 1.0.0
  description: API documentation for the Recipe App

tags:
  - name: categories
    description: Category management
  - name: recipes
    description: Recipe management

paths:
  /categories:
    get:
      summary: Get all categories
      tags:
        - categories
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '500':
          description: Server error

    post:
      summary: Create a new category
      tags:
        - categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Category created
        '400':
          description: Bad request
        '500':
          description: Server error

  /categories/{id}:
    get:
      summary: Get a category by ID
      tags:
        - categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Category not found
        '500':
          description: Server error

    put:
      summary: Update a category
      tags:
        - categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '200':
          description: Category updated
        '400':
          description: Bad request
        '404':
          description: Category not found
        '500':
          description: Server error

    delete:
      summary: Delete a category
      tags:
        - categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Category deleted
        '404':
          description: Category not found
        '500':
          description: Server error

  /recipes:
    get:
      summary: Get all recipes
      tags:
        - recipes
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
        '500':
          description: Server error

    post:
      summary: Create a new recipe
      tags:
        - recipes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeInput'
      responses:
        '201':
          description: Recipe created
        '400':
          description: Bad request
        '500':
          description: Server error

  /recipes/{id}:
    get:
      summary: Get a recipe by ID
      tags:
        - recipes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '404':
          description: Recipe not found
        '500':
          description: Server error

    put:
      summary: Update a recipe
      tags:
        - recipes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeInput'
      responses:
        '200':
          description: Recipe updated
        '400':
          description: Bad request
        '404':
          description: Recipe not found
        '500':
          description: Server error

    delete:
      summary: Delete a recipe
      tags:
        - recipes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Recipe deleted
        '404':
          description: Recipe not found
        '500':
          description: Server error

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    CategoryInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    Recipe:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        ingredients:
          type: array
          items:
            type: string
        instructions:
          type: array
          items:
            type: string
        categoryId:
          type: string

    RecipeInput:
      type: object
      required:
        - title
        - description
        - ingredients
        - instructions
        - categoryId
      properties:
        title:
          type: string
        description:
          type: string
        ingredients:
          type: string
        instructions:
          type: array
          items:
            type: string
        categoryId:
          type: string
